// Synonym map for common words
const synonymMap = {
  "big": ["substantial", "considerable", "significant", "extensive", "vast", "immense", "enormous", "sizable"],
  "small": ["minor", "modest", "diminutive", "compact", "minimal", "slight", "negligible", "trivial"],
  "good": ["excellent", "outstanding", "exceptional", "superior", "remarkable", "exemplary", "stellar", "superb"],
  "bad": ["poor", "substandard", "inadequate", "inferior", "deficient", "unsatisfactory", "problematic", "flawed"],
  "fast": ["rapid", "swift", "expedient", "prompt", "accelerated", "brisk", "efficient", "nimble"],
  "slow": ["gradual", "deliberate", "unhurried", "leisurely", "measured", "sluggish", "lethargic", "protracted"],
  "important": ["crucial", "essential", "vital", "critical", "significant", "paramount", "pivotal", "imperative"],
  "difficult": ["challenging", "complex", "demanding", "arduous", "formidable", "intricate", "rigorous", "taxing"],
  "easy": ["straightforward", "simple", "effortless", "uncomplicated", "manageable", "elementary", "accessible", "intuitive"],
  "use": ["utilize", "employ", "leverage", "harness", "apply", "implement", "adopt", "incorporate"],
  "make": ["create", "develop", "construct", "generate", "produce", "establish", "formulate", "devise"],
  "change": ["modify", "alter", "adjust", "transform", "revise", "adapt", "update", "refactor"],
  "fix": ["resolve", "address", "rectify", "remedy", "correct", "repair", "debug", "patch"],
  "help": ["assist", "facilitate", "support", "enable", "aid", "contribute to", "foster", "bolster"],
  "show": ["demonstrate", "illustrate", "display", "reveal", "exhibit", "present", "indicate", "convey"],
  "get": ["obtain", "acquire", "retrieve", "fetch", "procure", "secure", "access", "derive"],
  "think": ["consider", "contemplate", "evaluate", "assess", "analyze", "deliberate", "reflect on", "ponder"],
  "problem": ["issue", "challenge", "obstacle", "complication", "impediment", "concern", "difficulty", "setback"],
  "old": ["legacy", "outdated", "obsolete", "antiquated", "deprecated", "archaic", "dated", "previous"],
  "new": ["novel", "innovative", "contemporary", "modern", "fresh", "cutting-edge", "emerging", "recent"],
  "clear": ["evident", "apparent", "obvious", "unambiguous", "explicit", "transparent", "lucid", "distinct"],
  "very": ["exceptionally", "remarkably", "particularly", "extremely", "significantly", "considerably", "substantially", "notably"],
  "many": ["numerous", "multiple", "various", "several", "abundant", "myriad", "countless", "extensive"],
  "few": ["limited", "scarce", "sparse", "minimal", "handful of", "select", "rare", "occasional"],
  "start": ["initiate", "commence", "launch", "begin", "inaugurate", "kick off", "embark on", "trigger"],
  "end": ["conclude", "terminate", "finalize", "complete", "cease", "finish", "wrap up", "culminate"],
  "need": ["require", "necessitate", "demand", "call for", "warrant", "entail", "depend on", "rely on"],
  "want": ["desire", "seek", "aim for", "aspire to", "prefer", "favor", "wish for", "intend"],
  "try": ["attempt", "endeavor", "strive", "aim", "seek to", "undertake", "experiment with", "test"],
  "work": ["function", "operate", "perform", "execute", "run", "serve", "collaborate", "contribute"],
  "look": ["examine", "inspect", "observe", "review", "scrutinize", "analyze", "survey", "assess"],
  "tell": ["inform", "notify", "communicate", "convey", "relay", "disclose", "report", "announce"],
  "ask": ["inquire", "request", "query", "seek", "solicit", "petition", "probe", "question"],
  "give": ["provide", "offer", "supply", "deliver", "present", "grant", "bestow", "confer"],
  "take": ["acquire", "obtain", "accept", "receive", "seize", "capture", "secure", "procure"],
  "come": ["arrive", "approach", "emerge", "appear", "materialize", "reach", "attain", "surface"],
  "see": ["observe", "perceive", "notice", "recognize", "identify", "discern", "detect", "witness"],
  "know": ["understand", "comprehend", "recognize", "realize", "appreciate", "grasp", "acknowledge", "be aware of"],
  "like": ["appreciate", "enjoy", "favor", "prefer", "admire", "value", "relish", "be fond of"],
  "find": ["discover", "locate", "identify", "uncover", "detect", "encounter", "ascertain", "determine"],
  "move": ["relocate", "transfer", "shift", "transition", "migrate", "advance", "progress", "proceed"],
  "keep": ["maintain", "preserve", "retain", "sustain", "uphold", "continue", "persist", "safeguard"],
  "put": ["place", "position", "set", "situate", "deposit", "insert", "install", "establish"],
  "seem": ["appear", "look", "come across as", "give the impression", "suggest", "indicate", "imply", "convey"],
  "leave": ["depart", "exit", "abandon", "vacate", "withdraw", "forsake", "relinquish", "discontinue"],
  "call": ["contact", "reach out to", "summon", "convene", "designate", "refer to as", "label", "term"],
  "right": ["correct", "accurate", "appropriate", "proper", "suitable", "valid", "legitimate", "fitting"],
  "wrong": ["incorrect", "inaccurate", "erroneous", "mistaken", "flawed", "improper", "inappropriate", "faulty"],
  "real": ["genuine", "authentic", "actual", "true", "legitimate", "veritable", "bona fide", "substantial"],
  "different": ["distinct", "diverse", "varied", "alternative", "unique", "dissimilar", "divergent", "contrasting"],
  "same": ["identical", "equivalent", "uniform", "consistent", "matching", "comparable", "analogous", "corresponding"],
  "best": ["optimal", "ideal", "superior", "premier", "foremost", "preeminent", "paramount", "exemplary"],
  "first": ["initial", "primary", "foremost", "principal", "inaugural", "pioneering", "leading", "original"],
  "last": ["final", "ultimate", "concluding", "terminal", "closing", "definitive", "eventual", "remaining"],
  "long": ["extended", "prolonged", "lengthy", "extensive", "sustained", "enduring", "protracted", "considerable"],
  "great": ["exceptional", "remarkable", "outstanding", "excellent", "superb", "magnificent", "tremendous", "extraordinary"],
  "little": ["minimal", "slight", "modest", "minor", "marginal", "limited", "negligible", "nominal"],
  "own": ["possess", "have", "hold", "retain", "maintain", "command", "control", "keep"],
  "other": ["alternative", "additional", "different", "separate", "distinct", "remaining", "further", "supplementary"],
  "sure": ["certain", "confident", "convinced", "positive", "assured", "definite", "undoubted", "unquestionable"],
  "never": ["at no time", "not ever", "under no circumstances", "by no means", "not once", "not in any way"],
  "always": ["consistently", "invariably", "perpetually", "continuously", "constantly", "unfailingly", "reliably", "without exception"],
  "often": ["frequently", "regularly", "commonly", "repeatedly", "routinely", "habitually", "typically", "usually"],
  "also": ["additionally", "furthermore", "moreover", "likewise", "similarly", "as well", "besides", "too"],
  "just": ["merely", "simply", "only", "solely", "precisely", "exactly", "recently", "barely"],
  "now": ["currently", "presently", "at present", "at this time", "immediately", "promptly", "today", "nowadays"],
  "still": ["nevertheless", "nonetheless", "yet", "however", "even so", "regardless", "notwithstanding", "all the same"],
  "even": ["surprisingly", "remarkably", "indeed", "actually", "in fact", "as a matter of fact"],
  "much": ["considerably", "significantly", "substantially", "greatly", "extensively", "immensely", "vastly", "enormously"],
  "most": ["majority of", "predominantly", "primarily", "largely", "chiefly", "mainly", "principally", "for the most part"],
  "another": ["additional", "alternative", "different", "further", "supplementary", "extra", "one more", "other"],
  "become": ["evolve into", "transform into", "develop into", "turn into", "grow into", "emerge as", "transition to"],
  "because": ["since", "as", "due to", "owing to", "given that", "considering that", "in light of", "on account of"],
  "really": ["genuinely", "truly", "actually", "indeed", "certainly", "undoubtedly", "absolutely", "definitely"],
  "however": ["nevertheless", "nonetheless", "yet", "still", "conversely", "on the other hand", "that said", "even so"],
  "but": ["however", "nevertheless", "yet", "although", "though", "whereas", "while", "despite this"]
};

// Get synonyms for a word
function getSynonyms(word) {
  const lowerWord = word.toLowerCase().trim();
  return synonymMap[lowerWord] || [];
}

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { synonymMap, getSynonyms };
}

